### PR TITLE
Allow to pass additional arguments to the media play

### PR DESCRIPTION
**Pull request by bertwesarg**
I need to run the `playercast` service with a specific `mpv` argument, so that YT-DL videos wont use the best video quality, which caused to much CPU load. Now there is the `--player-args` option to pass additional arguments to the player.

### CODE REVIEW

**Comment by Rafostar** [comment]
Please use `~/.config/mpv/mpv.conf` file to achieve that.

MPV reads config from that file first then command line options (some that I had to preset in code) override that config (higher priority). This function was never implemented because it has a VERY big potential to breaking whole cast functionality by setting some cmd options. That is why user specific MPV config should be stored in `mpv.conf` file instead.

**Comment by bertwesarg** [comment]
Thanks for the suggestion. Though I still consider my user case valid, in case `mpv` is also used _normaly_ from the command line. Because than, the options needed for `playercast` may contradict the mode of operation from the command line. Thus to be independent from the use from the command line it may still make sense to have different options.

Luckily `mpv` knows _profiles_ inside the `mpv.conf` file. Thus I would like to suggest, that `mpv` is started always/optionally with the `--profile=playercast` (or some other name) argument and we document that `playercast` specific `mpv` arguments should be put into this profile? Unfortunately `mpv` exists, if the profile does not exists.

**Comment by Rafostar** [comment]
For now I will put this functionality on hold. Your use case is to restrict specific youtube codecs/resolution to play videos smoothly. You do not need player profiles to do that, because its not like mpv without playercast can play it smoothly anyway, so I do not see a reason to have this specific setting only for playercast and have laggy videos when using mpv normally without playercast...

Also please keep in mind that when new functionality is added it should be possible to use it in all supported media players (there might be more then 2 in the future). VLC as far as I know does not support player profiles and always uses config stored on system when it launches. That is why leaving machine specific options for user to manually configure inside player seems like best solution for the time being to me.

**Comment by bertwesarg** [comment]
I'm fine with this.

**Pull request closed without merging**
